name: CI Build

on:
  push:
    branches: [ main, master ]
    paths:
      - "**.cpp"
      - "**.h"
      - "**.pro"
      - "CMakeLists.txt"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main, master ]
    paths:
      - "**.cpp"
      - "**.h"
      - "**.pro"
      - "CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSVC Environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.5.*"
          modules: "qt5compat"
          cache: true

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Clouck-${{ runner.os }}-cmake
          path: build/Clouck*
